// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blog_service.proto

package proto

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Post model
type Post struct {
	Id                   uint64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Author               uint64      `protobuf:"varint,2,opt,name=author,proto3" json:"author,omitempty"`
	Title                string      `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              string      `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Timestemp            string      `protobuf:"bytes,5,opt,name=timestemp,proto3" json:"timestemp,omitempty"`
	Published            bool        `protobuf:"varint,6,opt,name=published,proto3" json:"published,omitempty"`
	Comments             []*Comments `protobuf:"bytes,7,rep,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_3979d75e20759271, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Post) GetAuthor() uint64 {
	if m != nil {
		return m.Author
	}
	return 0
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetTimestemp() string {
	if m != nil {
		return m.Timestemp
	}
	return ""
}

func (m *Post) GetPublished() bool {
	if m != nil {
		return m.Published
	}
	return false
}

func (m *Post) GetComments() []*Comments {
	if m != nil {
		return m.Comments
	}
	return nil
}

//Posts model
type Posts struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Posts) Reset()         { *m = Posts{} }
func (m *Posts) String() string { return proto.CompactTextString(m) }
func (*Posts) ProtoMessage()    {}
func (*Posts) Descriptor() ([]byte, []int) {
	return fileDescriptor_3979d75e20759271, []int{1}
}

func (m *Posts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Posts.Unmarshal(m, b)
}
func (m *Posts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Posts.Marshal(b, m, deterministic)
}
func (m *Posts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Posts.Merge(m, src)
}
func (m *Posts) XXX_Size() int {
	return xxx_messageInfo_Posts.Size(m)
}
func (m *Posts) XXX_DiscardUnknown() {
	xxx_messageInfo_Posts.DiscardUnknown(m)
}

var xxx_messageInfo_Posts proto.InternalMessageInfo

func (m *Posts) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

//comment model
type Comments struct {
	Author               uint64   `protobuf:"varint,1,opt,name=author,proto3" json:"author,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestemp            string   `protobuf:"bytes,3,opt,name=timestemp,proto3" json:"timestemp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comments) Reset()         { *m = Comments{} }
func (m *Comments) String() string { return proto.CompactTextString(m) }
func (*Comments) ProtoMessage()    {}
func (*Comments) Descriptor() ([]byte, []int) {
	return fileDescriptor_3979d75e20759271, []int{2}
}

func (m *Comments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comments.Unmarshal(m, b)
}
func (m *Comments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comments.Marshal(b, m, deterministic)
}
func (m *Comments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comments.Merge(m, src)
}
func (m *Comments) XXX_Size() int {
	return xxx_messageInfo_Comments.Size(m)
}
func (m *Comments) XXX_DiscardUnknown() {
	xxx_messageInfo_Comments.DiscardUnknown(m)
}

var xxx_messageInfo_Comments proto.InternalMessageInfo

func (m *Comments) GetAuthor() uint64 {
	if m != nil {
		return m.Author
	}
	return 0
}

func (m *Comments) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Comments) GetTimestemp() string {
	if m != nil {
		return m.Timestemp
	}
	return ""
}

//Posts serch by page num and by title
type PostsSearch struct {
	Page                 uint32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostsSearch) Reset()         { *m = PostsSearch{} }
func (m *PostsSearch) String() string { return proto.CompactTextString(m) }
func (*PostsSearch) ProtoMessage()    {}
func (*PostsSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_3979d75e20759271, []int{3}
}

func (m *PostsSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostsSearch.Unmarshal(m, b)
}
func (m *PostsSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostsSearch.Marshal(b, m, deterministic)
}
func (m *PostsSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostsSearch.Merge(m, src)
}
func (m *PostsSearch) XXX_Size() int {
	return xxx_messageInfo_PostsSearch.Size(m)
}
func (m *PostsSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_PostsSearch.DiscardUnknown(m)
}

var xxx_messageInfo_PostsSearch proto.InternalMessageInfo

func (m *PostsSearch) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PostsSearch) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

//Response post with data
type ResponsePost struct {
	StatusCode           uint32   `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Post                 *Post    `protobuf:"bytes,3,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponsePost) Reset()         { *m = ResponsePost{} }
func (m *ResponsePost) String() string { return proto.CompactTextString(m) }
func (*ResponsePost) ProtoMessage()    {}
func (*ResponsePost) Descriptor() ([]byte, []int) {
	return fileDescriptor_3979d75e20759271, []int{4}
}

func (m *ResponsePost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponsePost.Unmarshal(m, b)
}
func (m *ResponsePost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponsePost.Marshal(b, m, deterministic)
}
func (m *ResponsePost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponsePost.Merge(m, src)
}
func (m *ResponsePost) XXX_Size() int {
	return xxx_messageInfo_ResponsePost.Size(m)
}
func (m *ResponsePost) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponsePost.DiscardUnknown(m)
}

var xxx_messageInfo_ResponsePost proto.InternalMessageInfo

func (m *ResponsePost) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ResponsePost) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResponsePost) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

//Request Post by ID
type RequestPost struct {
	PostID               uint64   `protobuf:"varint,1,opt,name=postID,proto3" json:"postID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestPost) Reset()         { *m = RequestPost{} }
func (m *RequestPost) String() string { return proto.CompactTextString(m) }
func (*RequestPost) ProtoMessage()    {}
func (*RequestPost) Descriptor() ([]byte, []int) {
	return fileDescriptor_3979d75e20759271, []int{5}
}

func (m *RequestPost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestPost.Unmarshal(m, b)
}
func (m *RequestPost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestPost.Marshal(b, m, deterministic)
}
func (m *RequestPost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestPost.Merge(m, src)
}
func (m *RequestPost) XXX_Size() int {
	return xxx_messageInfo_RequestPost.Size(m)
}
func (m *RequestPost) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestPost.DiscardUnknown(m)
}

var xxx_messageInfo_RequestPost proto.InternalMessageInfo

func (m *RequestPost) GetPostID() uint64 {
	if m != nil {
		return m.PostID
	}
	return 0
}

func init() {
	proto.RegisterType((*Post)(nil), "proto.Post")
	proto.RegisterType((*Posts)(nil), "proto.Posts")
	proto.RegisterType((*Comments)(nil), "proto.Comments")
	proto.RegisterType((*PostsSearch)(nil), "proto.PostsSearch")
	proto.RegisterType((*ResponsePost)(nil), "proto.ResponsePost")
	proto.RegisterType((*RequestPost)(nil), "proto.RequestPost")
}

func init() { proto.RegisterFile("blog_service.proto", fileDescriptor_3979d75e20759271) }

var fileDescriptor_3979d75e20759271 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0xaa, 0x9b, 0x40,
	0x14, 0x45, 0xa3, 0xc6, 0x5c, 0xd3, 0x16, 0xa6, 0x25, 0x0c, 0xa1, 0xb4, 0x56, 0x28, 0x48, 0x5b,
	0x5c, 0xa4, 0x94, 0xee, 0x9b, 0x6e, 0xba, 0x2b, 0x93, 0x5d, 0x37, 0xc5, 0xe8, 0xc5, 0x08, 0xea,
	0x58, 0x67, 0xec, 0x2f, 0xbc, 0x4f, 0x7b, 0xbf, 0xf5, 0x98, 0x71, 0x4c, 0xe6, 0x85, 0xc7, 0x23,
	0x2b, 0xe7, 0x9e, 0x3b, 0xe7, 0x78, 0xce, 0x51, 0x20, 0xc7, 0x86, 0x57, 0x7f, 0x05, 0x0e, 0xff,
	0xeb, 0x02, 0xb3, 0x7e, 0xe0, 0x92, 0x13, 0x5f, 0x3f, 0x92, 0x7b, 0x07, 0xbc, 0xdf, 0x5c, 0x48,
	0xf2, 0x12, 0xdc, 0xba, 0xa4, 0x4e, 0xec, 0xa4, 0x1e, 0x73, 0xeb, 0x92, 0x6c, 0x20, 0xc8, 0x47,
	0x79, 0xe2, 0x03, 0x75, 0x35, 0x66, 0x26, 0xf2, 0x06, 0x7c, 0x59, 0xcb, 0x06, 0xe9, 0x22, 0x76,
	0xd2, 0x15, 0x9b, 0x06, 0x42, 0x61, 0x59, 0xf0, 0x4e, 0x62, 0x27, 0xa9, 0xa7, 0xf1, 0x79, 0x24,
	0x6f, 0x61, 0x25, 0xeb, 0x16, 0x85, 0xc4, 0xb6, 0xa7, 0xbe, 0xde, 0x5d, 0x00, 0xb5, 0xed, 0xc7,
	0x63, 0x53, 0x8b, 0x13, 0x96, 0x34, 0x88, 0x9d, 0x34, 0x64, 0x17, 0x80, 0x7c, 0x86, 0xb0, 0xe0,
	0x6d, 0x8b, 0x9d, 0x14, 0x74, 0x19, 0x2f, 0xd2, 0x68, 0xf7, 0x6a, 0x72, 0x9f, 0xed, 0x0d, 0xcc,
	0xce, 0x17, 0x92, 0x4f, 0xe0, 0xab, 0x20, 0x82, 0x7c, 0x00, 0xbf, 0x57, 0x07, 0xea, 0x68, 0x4a,
	0x64, 0x28, 0x6a, 0xc9, 0xa6, 0x4d, 0xf2, 0x07, 0xc2, 0x59, 0xc1, 0x0a, 0xea, 0x3c, 0x0a, 0x6a,
	0x45, 0x72, 0x9f, 0x89, 0xb4, 0xb8, 0x8a, 0x94, 0x7c, 0x87, 0x48, 0xfb, 0x38, 0x60, 0x3e, 0x14,
	0x27, 0x42, 0xc0, 0xeb, 0xf3, 0x0a, 0xb5, 0xf8, 0x0b, 0xa6, 0xcf, 0x97, 0x0e, 0x5d, 0xab, 0xc3,
	0xa4, 0x86, 0x35, 0x43, 0xd1, 0xf3, 0x4e, 0xa0, 0xfe, 0x22, 0xef, 0x00, 0x84, 0xcc, 0xe5, 0x28,
	0xf6, 0xbc, 0x9c, 0xf9, 0x16, 0xa2, 0x0c, 0xb6, 0x28, 0x84, 0x12, 0x37, 0x06, 0xcd, 0x48, 0xde,
	0x83, 0xa7, 0x72, 0x6a, 0x6f, 0x57, 0x05, 0xe8, 0x45, 0xf2, 0x11, 0x22, 0x86, 0xff, 0x46, 0x14,
	0x52, 0xbf, 0x69, 0x03, 0x81, 0x82, 0x7f, 0xfd, 0x9c, 0x2b, 0x98, 0xa6, 0xdd, 0x9d, 0x0b, 0xeb,
	0x1f, 0x0d, 0xaf, 0x0e, 0xd3, 0x9f, 0x23, 0xc8, 0x0e, 0x96, 0x15, 0x4e, 0x1c, 0x62, 0x54, 0x2d,
	0x9d, 0xed, 0xeb, 0x33, 0x66, 0xc5, 0xf8, 0x02, 0xa1, 0xe1, 0x88, 0x33, 0xc9, 0x2a, 0x68, 0xbb,
	0xb6, 0x31, 0x92, 0x01, 0x14, 0x03, 0xe6, 0x72, 0xe2, 0xda, 0xd6, 0x9f, 0x56, 0xcf, 0x00, 0xc6,
	0xbe, 0xbc, 0xfd, 0xfe, 0x37, 0x80, 0x12, 0x1b, 0x34, 0xf7, 0x6f, 0x0d, 0x71, 0x0c, 0x34, 0xf6,
	0xf5, 0x21, 0x00, 0x00, 0xff, 0xff, 0x13, 0x89, 0x27, 0x05, 0x4a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlogServicesClient is the client API for BlogServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlogServicesClient interface {
	//get single post
	GetPost(ctx context.Context, in *RequestPost, opts ...grpc.CallOption) (*ResponsePost, error)
	//get list of posts
	GetPosts(ctx context.Context, in *PostsSearch, opts ...grpc.CallOption) (*Posts, error)
	//create a post
	CreatePost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*ResponsePost, error)
	//update a post
	UpdatePost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*ResponsePost, error)
	//delete a post
	DeletePost(ctx context.Context, in *RequestPost, opts ...grpc.CallOption) (*ResponsePost, error)
}

type blogServicesClient struct {
	cc *grpc.ClientConn
}

func NewBlogServicesClient(cc *grpc.ClientConn) BlogServicesClient {
	return &blogServicesClient{cc}
}

func (c *blogServicesClient) GetPost(ctx context.Context, in *RequestPost, opts ...grpc.CallOption) (*ResponsePost, error) {
	out := new(ResponsePost)
	err := c.cc.Invoke(ctx, "/proto.BlogServices/getPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServicesClient) GetPosts(ctx context.Context, in *PostsSearch, opts ...grpc.CallOption) (*Posts, error) {
	out := new(Posts)
	err := c.cc.Invoke(ctx, "/proto.BlogServices/getPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServicesClient) CreatePost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*ResponsePost, error) {
	out := new(ResponsePost)
	err := c.cc.Invoke(ctx, "/proto.BlogServices/createPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServicesClient) UpdatePost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*ResponsePost, error) {
	out := new(ResponsePost)
	err := c.cc.Invoke(ctx, "/proto.BlogServices/updatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServicesClient) DeletePost(ctx context.Context, in *RequestPost, opts ...grpc.CallOption) (*ResponsePost, error) {
	out := new(ResponsePost)
	err := c.cc.Invoke(ctx, "/proto.BlogServices/deletePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogServicesServer is the server API for BlogServices service.
type BlogServicesServer interface {
	//get single post
	GetPost(context.Context, *RequestPost) (*ResponsePost, error)
	//get list of posts
	GetPosts(context.Context, *PostsSearch) (*Posts, error)
	//create a post
	CreatePost(context.Context, *Post) (*ResponsePost, error)
	//update a post
	UpdatePost(context.Context, *Post) (*ResponsePost, error)
	//delete a post
	DeletePost(context.Context, *RequestPost) (*ResponsePost, error)
}

// UnimplementedBlogServicesServer can be embedded to have forward compatible implementations.
type UnimplementedBlogServicesServer struct {
}

func (*UnimplementedBlogServicesServer) GetPost(ctx context.Context, req *RequestPost) (*ResponsePost, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPost not implemented")
}
func (*UnimplementedBlogServicesServer) GetPosts(ctx context.Context, req *PostsSearch) (*Posts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPosts not implemented")
}
func (*UnimplementedBlogServicesServer) CreatePost(ctx context.Context, req *Post) (*ResponsePost, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (*UnimplementedBlogServicesServer) UpdatePost(ctx context.Context, req *Post) (*ResponsePost, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePost not implemented")
}
func (*UnimplementedBlogServicesServer) DeletePost(ctx context.Context, req *RequestPost) (*ResponsePost, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}

func RegisterBlogServicesServer(s *grpc.Server, srv BlogServicesServer) {
	s.RegisterService(&_BlogServices_serviceDesc, srv)
}

func _BlogServices_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServicesServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BlogServices/GetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServicesServer).GetPost(ctx, req.(*RequestPost))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogServices_GetPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostsSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServicesServer).GetPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BlogServices/GetPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServicesServer).GetPosts(ctx, req.(*PostsSearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogServices_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServicesServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BlogServices/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServicesServer).CreatePost(ctx, req.(*Post))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogServices_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServicesServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BlogServices/UpdatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServicesServer).UpdatePost(ctx, req.(*Post))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogServices_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServicesServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BlogServices/DeletePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServicesServer).DeletePost(ctx, req.(*RequestPost))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlogServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BlogServices",
	HandlerType: (*BlogServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getPost",
			Handler:    _BlogServices_GetPost_Handler,
		},
		{
			MethodName: "getPosts",
			Handler:    _BlogServices_GetPosts_Handler,
		},
		{
			MethodName: "createPost",
			Handler:    _BlogServices_CreatePost_Handler,
		},
		{
			MethodName: "updatePost",
			Handler:    _BlogServices_UpdatePost_Handler,
		},
		{
			MethodName: "deletePost",
			Handler:    _BlogServices_DeletePost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog_service.proto",
}
